### ISSUE TITLE
Easy start with templates and assets

### ISSUE THREAD

**Issue by bastianccm** [i-love-flamingo/flamingo#124]
Document the minimum requirements such as:
```go
package main

import (
	"flamingo.me/dingo"
	"flamingo.me/flamingo/v3"
	"flamingo.me/flamingo/v3/core/gotemplate"
)

func main() {
	flamingo.App([]dingo.Module{
		new(gotemplate.Module),
	})
}
```

```yaml
- name: index
  path: /
  controller: flamingo.render(tpl="index")
- name: static
  path: /asset/*name
  controller: flamingo.static.file
```
